const vk = @import("vulkan");

const enable_validation_layers = switch (@import("builtin").mode) {
    .Debug => true,
    else => false,
};

const apis: []const vk.ApiInfo = &.{
    .{
        .base_commands = .{
            .createInstance = true,
            .enumerateInstanceExtensionProperties = true,
            .enumerateInstanceLayerProperties = enable_validation_layers,
            .getInstanceProcAddr = true,
        },
        .instance_commands = .{
            .destroyInstance = true,
            .createDevice = true,
            .destroySurfaceKHR = true,
            .enumeratePhysicalDevices = true,
            .getPhysicalDeviceProperties = true,
            .enumerateDeviceExtensionProperties = true,
            .getPhysicalDeviceSurfaceFormatsKHR = true,
            .getPhysicalDeviceSurfacePresentModesKHR = true,
            .getPhysicalDeviceSurfaceCapabilitiesKHR = true,
            .getPhysicalDeviceQueueFamilyProperties = true,
            .getPhysicalDeviceSurfaceSupportKHR = true,
            .getPhysicalDeviceMemoryProperties = true,
            .getDeviceProcAddr = true,
        },
        .device_commands = .{
            .destroyDevice = true,
            .getDeviceQueue = true,
            .createSemaphore = true,
            .createFence = true,
            .createImageView = true,
            .destroyImageView = true,
            .destroySemaphore = true,
            .destroyFence = true,
            .getSwapchainImagesKHR = true,
            .createSwapchainKHR = true,
            .destroySwapchainKHR = true,
            .acquireNextImageKHR = true,
            .deviceWaitIdle = true,
            .waitForFences = true,
            .resetFences = true,
            .queueSubmit = true,
            .queuePresentKHR = true,
            .createCommandPool = true,
            .destroyCommandPool = true,
            .allocateCommandBuffers = true,
            .freeCommandBuffers = true,
            .queueWaitIdle = true,
            .createShaderModule = true,
            .destroyShaderModule = true,
            .createPipelineLayout = true,
            .destroyPipelineLayout = true,
            .createRenderPass = true,
            .destroyRenderPass = true,
            .createGraphicsPipelines = true,
            .destroyPipeline = true,
            .createFramebuffer = true,
            .destroyFramebuffer = true,
            .beginCommandBuffer = true,
            .endCommandBuffer = true,
            .allocateMemory = true,
            .freeMemory = true,
            .createBuffer = true,
            .destroyBuffer = true,
            .getBufferMemoryRequirements = true,
            .mapMemory = true,
            .unmapMemory = true,
            .bindBufferMemory = true,
            .cmdBeginRenderPass = true,
            .cmdEndRenderPass = true,
            .cmdBindPipeline = true,
            .cmdDraw = true,
            .cmdSetViewport = true,
            .cmdSetScissor = true,
            .cmdBindVertexBuffers = true,
            .cmdCopyBuffer = true,
        },
    },
};

pub const BaseDispatch = vk.BaseWrapper(apis);

pub const InstanceDispatch = vk.InstanceWrapper(apis);

pub const DeviceDispatch = vk.DeviceWrapper(apis);
